package com.harshith.urlshortner.resource;

import java.net.URI;
import java.net.URISyntaxException;
import java.util.List;
import javax.servlet.http.HttpServletResponse;
import javax.validation.constraints.Max;
import javax.validation.constraints.Min;
import javax.ws.rs.core.Response;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.http.HttpStatus;
import org.springframework.http.ResponseEntity;
import org.springframework.web.bind.annotation.GetMapping;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RequestParam;
import org.springframework.web.bind.annotation.RestController;
import org.springframework.web.servlet.ModelAndView;
import com.harshith.urlshortner.enums.SortByColumnEnum;
import com.harshith.urlshortner.enums.SortOrderEnum;
import com.harshith.urlshortner.factory.UrlShortnerFactory;
import com.harshith.urlshortner.service.UrlShortnerServiceException;
import com.harshith.urlshortner.view.UrlShortenResponseView;
import io.swagger.annotations.Api;
import io.swagger.annotations.ApiOperation;
import io.swagger.annotations.ApiParam;


/**
 * This resource handles the photo related operations for Legacy SSO based approach.
 */

@Api(value = "URL Shortner Operations", tags = "URL Shortner APIs ")
@RestController
@RequestMapping("/v1")
public class UrlShortnerResource {


  @Autowired
  private UrlShortnerFactory urlShortnerFactory;


  @ApiOperation(value = "Shorten the URL by Unique ID generated by DB Sequence",
      response = String.class)
  @GetMapping(path = "/shorten")
  public String getShortenedUrl(@ApiParam("Original Url") @RequestParam(value = "original_url",
      required = true) String originalUrl) throws UrlShortnerServiceException {
    return urlShortnerFactory.getShortenedUrl(originalUrl);
  }


  @ApiOperation(value = "Shorten the URL by Unique current date time", response = String.class)
  @GetMapping(path = "/shortenbydate")
  public String getShortenedUrlByUniqueDate(
      @ApiParam("Original Url") @RequestParam(value = "original_url",
          required = true) String originalUrl)
      throws UrlShortnerServiceException {
    return urlShortnerFactory.getShortenedUrlByUniqueDate(originalUrl);
  }


  @ApiOperation(value = "Fetch the Original URL for the Short URL",
      response = UrlShortenResponseView.class)
  @GetMapping(value = "/original")
  public UrlShortenResponseView getOriginalUrl(
      @ApiParam("Shortened Url") @RequestParam(value = "shortened_url",
          required = true) String shortenedUrl)
      throws UrlShortnerServiceException {
    return urlShortnerFactory.getOriginalUrl(shortenedUrl);
  }


  @ApiOperation(value = "Fetch the Original URLs list details",
      response = UrlShortenResponseView.class, responseContainer = "List")
  @GetMapping(value = "/original-list")
  public List<UrlShortenResponseView> getOriginalUrlList(
      @Min(value = 1, message = "page_number must be minimum 1") @RequestParam(
          value = "page_number", defaultValue = "1") int pageNumber,
      @Max(value = 100, message = "page_size can be at max 100") @RequestParam(value = "page_size",
          defaultValue = "20") int pageSize,
      @RequestParam(value = "sort_by", defaultValue = "CREATED_DATE") SortByColumnEnum sortBy,
      @RequestParam(value = "sort_by_order", defaultValue = "DESC") SortOrderEnum sortByOrder)
      throws UrlShortnerServiceException {
    return urlShortnerFactory.getOriginalUrlList(pageNumber, pageSize, sortBy, sortByOrder);
  }


  @ApiOperation(value = "Redirect to actual URL with URI Response Approach",
      response = Response.class)
  @GetMapping(value = "/redirect-response")
  public Response redirectToOriginalUrl(
      @ApiParam("Shortened Url") @RequestParam(value = "shortened_url",
          required = true) String shortenedUrl)
      throws UrlShortnerServiceException, URISyntaxException {
    return urlShortnerFactory.redirectToOriginalUrl(shortenedUrl);
  }

  @ApiOperation(value = "Redirect to actual URL with Servlet Approach",
      response = ModelAndView.class)
  @GetMapping(value = "/redirect-servlet")
  public ModelAndView redirectToOriginalUrlNew(
      @ApiParam("Shortened Url") @RequestParam(value = "shortened_url",
          required = true) String shortenedUrl,
      HttpServletResponse httpServletResponse)
      throws UrlShortnerServiceException, URISyntaxException {
    return urlShortnerFactory.redirectToOriginalUrlNew(shortenedUrl, httpServletResponse);
  }

  @ApiOperation(value = "Redirect to actual URL")
  @GetMapping(value = "/redirect-responseentity")
  public ResponseEntity<Void> getAndRedirect(
      @ApiParam("Shortened Url") @RequestParam(value = "shortened_url",
          required = true) String shortenedUrl)
      throws UrlShortnerServiceException {
    String url = urlShortnerFactory.getOriginalUrl(shortenedUrl).getOriginalUrl();
    return ResponseEntity.status(HttpStatus.FOUND).location(URI.create(url)).build();
  }


}
