package com.harshith.urlshortner.resource;

import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.web.bind.annotation.GetMapping;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RequestParam;
import org.springframework.web.bind.annotation.RestController;
import com.harshith.urlshortner.factory.UrlShortnerFactory;
import com.harshith.urlshortner.service.UrlShortnerServiceException;
import io.swagger.annotations.Api;
import io.swagger.annotations.ApiOperation;
import io.swagger.annotations.ApiParam;


/**
 * This resource handles the URL Shortener Operations for the Original URLs provided.
 */

@Api(value = "URL Shortner Operations", tags = "URL Shortner APIs")
@RestController
@RequestMapping("/v1/shorten")
public class UrlShortnerResource {

  @Autowired
  private UrlShortnerFactory urlShortnerFactory;


  @ApiOperation(value = "Shorten the URL by Unique ID generated by DB Sequence",
      response = String.class)
  @GetMapping(path = "/by-id")
  public String getShortenedUrl(@ApiParam("Original Url") @RequestParam(value = "original_url",
      required = true) String originalUrl) throws UrlShortnerServiceException {
    return urlShortnerFactory.getShortenedUrl(originalUrl);
  }


  @ApiOperation(value = "Shorten the URL by Unique current date time", response = String.class)
  @GetMapping(path = "/by-date")
  public String getShortenedUrlByUniqueDate(
      @ApiParam("Original Url") @RequestParam(value = "original_url",
          required = true) String originalUrl)
      throws UrlShortnerServiceException {
    return urlShortnerFactory.getShortenedUrlByUniqueDate(originalUrl);
  }

}
